/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env= --include-runtime=false --strict-vars=false --env-interface=GeneratedLeaderboardBindings` (hash: eb0fa2a7010c4c27edb61dd1ffc5e0e4)
interface __BaseEnv_GeneratedLeaderboardBindings {
	SOCIAL_DB: D1Database;
	ERASURE_DB: D1Database;
	PROJECTION_1: D1Database;
	SOCIAL_OUTBOX: Queue;
	ENV_NAME: string;
	APP_BUNDLE_ID: string;
	APP_SLUG: string;
	SOCIAL_OUTBOX_QUEUE: string;
	INVITE_LINK_BASE: string;
	SOCIAL_JWT_SECRET: string;
	IDENTITY_HMAC_KEY_V1: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface DevEnv {
		SOCIAL_DB: D1Database;
		ERASURE_DB: D1Database;
		PROJECTION_1: D1Database;
		SOCIAL_OUTBOX: Queue;
		ENV_NAME: string;
		APP_BUNDLE_ID: string;
		APP_SLUG: string;
		SOCIAL_OUTBOX_QUEUE: string;
		INVITE_LINK_BASE: string;
		SOCIAL_JWT_SECRET: string;
		IDENTITY_HMAC_KEY_V1: string;
	}
	interface Env extends __BaseEnv_GeneratedLeaderboardBindings {}
}
interface GeneratedLeaderboardBindings extends __BaseEnv_GeneratedLeaderboardBindings {}
