name = "german-vocabulary-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "german-vocabulary"
database_id = "b84997d9-5e78-493e-a43e-9d8aafd1ca95"

[observability]
enabled = true
